// <auto-generated />
namespace LearningPlatform.Data.EntityFramework.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_Something : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Something));
        
        string IMigrationMetadata.Id
        {
            get { return "201712190443441_Change_Something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
